/*
	This function is here only to remove the annoying
	"variable X only referenced once" message by referencing
	every function on this extensions.
	Even the experimental and optional ones.
	
	You can ignore all contents of this file.
*/
function __gml_ext_opt_lib_remove_unused_msg() {
  try {
    var _ = [
      __gml_ext_opt_lib_remove_unused_msg,
      getPixel,
      getPixelExt,
      drawPart,
      drawStretched,
      getHeight,
      server_tcp_send_ping,
      Logger,
      warn,
      getSize,
      isNineslice,
      getFrames,
      getSpriteType,
      getUVS,
      clear,
      resize,
      link_instance,
      getOrigin,
      url,
      header,
      free,
      layer_get_background,
      exists,
      layer_get_tileset,
      error,
      filename,
      close,
      getMessages,
      layer_get_element_ids_fixed,
      http_async_get_message,
      http_async_handle_request,
      view_get_x,
      view_get_y,
      anim_easeInBack,
      anim_easeInBounce,
      anim_easeInCirc,
      anim_easeInCubic,
      anim_easeInCubic,
      anim_easeInElastic,
      anim_easeInExpo,
      anim_easeInQuad,
      anim_easeInQuart,
      anim_easeInQuint,
      anim_easeInOutBack,
      anim_easeInOutBounce,
      anim_easeInOutCirc,
      anim_easeInOutCubic,
      anim_easeInOutCubic,
      anim_easeInOutElastic,
      anim_easeInOutExpo,
      anim_easeInOutQuad,
      anim_easeInOutQuart,
      anim_easeInOutQuint,
      anim_easeInOutSine,
      anim_easeOutBack,
      anim_easeOutBounce,
      anim_easeOutCirc,
      anim_easeOutCubic,
      anim_easeOutCubic,
      anim_easeOutElastic,
      anim_easeOutExpo,
      anim_easeOutQuad,
      anim_easeOutQuart,
      anim_easeOutQuint,
      anim_easeOutSine,
      struct_equal,
      instance_get_if,
      instance_get_all,
      drawTiled,
      del,
      header_values,
      http_request_send,
      string_percentage,
      instance_create,
      instance_create_unique,
      YYYY,
      YY,
      MM,
      DD,
      mm,
      dd,
      day,
      m,
      d,
      D,
      H,
      NN,
      M,
      HH,
      year,
      month,
      hour,
      minute,
      second,
      Sprite,
      instance_any_exists,
      instance_in_room,
      alert,
      alert_async,
      string_title,
      event_user_exec,
      str,
      file_text_get_lines_array,
      result,
      ROT,
      draw_fps,
      draw_fps_real,
      color_get_rgb,
      save,
      Surface,
      draw,
      getWidth,
      current_week,
      current_day_of_year,
      time_performance,
      SS,
      weekday,
      int16,
      int16s,
      int8s,
      instance_number_if,
      draw_set_profile,
      draw_rectangle_width,
      draw_create_profile,
      draw_text_shadow,
      draw_surface_from_center,
      draw_text_size,
      draw_set_gui_scale,
      draw_text_outline,
      gpu_set_alpha_overwrite,
      draw_rectangle_rotated,
      draw_reset,
      draw_quad,
      u_int,
      draw_surface_blur,
      u_texture,
      draw_sprite_recolor,
      draw_sprite_blur,
      draw_surface_recolor,
      choice_weighted,
      near,
      rng,
      uuid_v4,
      between,
      mouse_in_area,
      mouse_in_instance,
      mouse_is_moving,
      mouse_in_gui_area,
      json2file,
      _iteration,
      struct_copy,
      string_fill_zero,
      file_to_json,
      array_write,
      __gml_ext_comp_init,
      as_string,
      image_set_scale,
      image_loop_index,
      image_set,
      image_smooth_rotate,
      game_get_param_value,
      game_throw_error,
      game_get_param_exists,
      array_empty,
      array_to_ds_list,
      array_to_struct,
      array_fill,
      array_clear,
      ds_list_to_array,
      server_tcp_init,
      server_tcp_get_data,
      rgba_dec2hex,
      color_rgba_get_alpha,
      dec_rgb2rgba,
      json2yy,
      color_get_hsv,
      hsv,
      rgb,
      getBboxMode,
      getFramesInfo,
      getBbox,
      alpha,
      vAlign,
      blendmode,
      hAlign,
      font,
      current_draw_valign,
      current_draw_alpha,
      current_draw_color,
      current_draw_halign,
      current_draw_font,
      gui_height,
      gui_width,
      anim_easeInSine,
      GM_VERSION_IS_2024,
      sort_ascending,
      sort_descending,
      sort_elem_size_desc,
      SERVER_PORT,
      BUFFER_SIZE,
      open,
      layer_element_type_sprite,
      layer_element_type_tilemap_old,
      layer_element_type_instance,
      layer_element_type_undefined,
      layer_element_type_background,
      layer_element_type_tile,
      layer_element_type_sequence,
      layer_element_type_particle_system,
      http_method_post,
      http_method_put,
      http_method_delete,
      gm_type_reference,
      null,
    ];
	
	frame_info = noone;
	subimages = noone;
	xoffset = noone;
	yoffset = noone;
	
	builtin = {};
	builtin.gpu_set_depth = noone;
	builtin.window_mouse_get_delta_x = noone;
	builtin.window_mouse_get_delta_y = noone;
	builtin.array_contains = noone;
	builtin.is_callable = noone;
	builtin.string_split = noone;
	builtin.time_source_units_frames = noone;
	builtin.time_source_units_seconds = noone;
	builtin.variable_clone = noone;
	builtin.string_ext = noone;
	
	} finally {
    // This does nothing!
  }

  return _;
}
